### ISSUE TITLE
logout 요청 필요

### ISSUE THREAD

**Issue by yypp1226** [ucharles/Comrade#10]
@ucharles 
서버쪽에서 httponly로 쿠키 저장 시, 클라이언트 쪽에서는 접근이 불가하니 로그아웃시 쿠키삭제처리 등을 서버쪽에서 해야합니다. (로그아웃 요청을 보내야함) 

로그아웃 라우터 추가 부탁드립니다.

**Comment by ucharles** [comment]
추가 후 이슈 갱신하도록 하겠습니다. 감사합니다.

**Comment by ucharles** [comment]
GET 요청으로 Logout API를 호출할 수 있습니다.
- 모든 쿠키 삭제 (Token, LoggedIn)
- 별도의 JSON 값을 리턴하지 않음
