### ISSUE TITLE
/api/users/token-check 가 동시에 2번 호출될 경우 2번째 요청은 403 에러를 반환

### ISSUE THREAD

**Issue by ucharles** [ucharles/Comrade#27]
## 현상
1. 루트 경로(`/`)에서 `getPermission`이 2번 호출되고 있음.
2. `getPermission`에서 `/api/users/token-check`을 동시에 2번 호출.
3. 1번째 응답은 정상, 2번째 응답은 에러.

## 원인(추측)
1. Refresh Token이 7일 이하로 남으면 DB update가 일어남.
2. 백엔드 코드가 잘못되어 매 요청마다 DB update가 일어나고 있었음. (에러의 직접적인 원인은 아님)
3. 동일한 Refresh Token으로 `getPermission`에서 `/api/users/token-check`을 동시에 2번 호출.
4. 1번째 요청은 정상적으로 처리되어 DB가 update 됨.
5. 2번째 요청은 update된 DB 정보를 반영하지 못한 채 일어나므로, 에러로 응답.

## 해결책
- `getPermission`에 `async/await` 추가?
    - 실험결과, 효과 없음 
- `getPermission`이 동시에 1번만 일어나도록 하게 함.
    -  루트 경로(`/`)를 `<CustomRoutes>`로 이동

### 관련 이슈
https://github.com/ucharles/Comrade/issues/8 Refresh Token 적용하기

**Comment by ucharles** [comment]
백엔드 수정 완료 https://github.com/ucharles/Comrade/commit/0e32efbcdd07dfc738d304dcb25d1ab28aca3204

**Comment by yypp1226** [comment]
수정 확인 했습니다~ 감사합니다

**Comment by ucharles** [comment]
https://github.com/ucharles/Comrade/commit/30d0e944f48a23bc13080158da27fc179513dd34
백엔드의 check-auth에서 DB update(refresh token 갱신)을 하지 않도록 변경.
또한, loggedIn 쿠키를 추가하여 API 접근을 줄이고자 함.
(loggedIn 쿠키: 브라우저 읽기 가능. refresh token과 같은 갱신주기, 없을 경우 강제 로그아웃)

이 변경사항으로 refresh token 갱신 타이밍에 token-check API가 동시에 2번 호출되어도 403 에러를 반환하지 않음.
Close 하겠습니다.
