### ISSUE TITLE
Join Calendar의 입력 필드에 대해

### ISSUE THREAD

**Issue by ucharles** [ucharles/Comrade#29]
확인이 늦어서 죄송합니다. 이하의 수정이 필요합니다.
수정은 @ucharles 가 진행하도록 하겠습니다. @yypp1226 확인만 부탁드립니다.
관련 이슈 #16 #23

## 현재
Nickname, Timezone 입력을 받고 있음

## 향후
- 입력 필드는 Role과 Nickname
- Role은 관리자, 멤버를 구분하는 것이 아님. 그룹 안의 역할을 의미함. 필수 입력 아님. Null 가능.
- Timezone은 로그인 시 쿠키에 저장. DB에 저장하지 않음.
- Timezone 입력 시 사용하는 라이브러리에 이슈가 있으므로 사용을 보류
- Timezone 편집이 필요하다면 유저 설정에서 일괄적으로 이루어져야 함.
- 달력별로 Timezone을 다르게 설정할 경우엔 데이터의 저장 방법 검토가 필요함. (Cookie? Local Storage?)

**Comment by ucharles** [comment]
@yypp1226 이모지는 알림이 오지 않기 때문에 확인은 댓글로 부탁드립니다. (ㅜㅜ)

**Comment by yypp1226** [comment]
@ucharles 확인했습니다~
