### ISSUE TITLE
웹 서버가 보낸 쿠키가 클라이언트에 저장되지 않음

### ISSUE THREAD

**Issue by ucharles** [ucharles/Comrade#7]
@yypp1226 
**관련 코드 commit 시 이 이슈 번호 추가하시고, 이슈 close 시 관련 commit 링크 부탁드립니다.**

프론트 쪽 API 요청에 이하를 추가하십시오.

`credentials: "include"`

ex)

```
const request = new Request(
  process.env.REACT_APP_BACKEND_URL + "/users/login",
  {
    method: "POST",
    body: JSON.stringify({ email, password }),
    headers: new Headers({ "Content-Type": "application/json" }),
    credentials: "include",
  }
```

참조: https://developer.mozilla.org/ko/docs/Web/API/Request/credentials

**Comment by yypp1226** [comment]
#21 반영했습니다 감사합니다
